baseURL: "https://vdutor.github.io/dap-rosdamhoeve-hugo"
canonifyurls: true
languageCode: "nl-be"
title: "DAP Rosdamhoeve"

params:
  description: "Website Dierenartsenpraktijk Rosdamhoeve"
  author: "DAP Rosdamhoeve"

defaultContentLanguageInSubdir: false
defaultContentLanguage: nl
languages:
  nl:
    contentDir: content/nl
    languageName: Nederlands
    languageCode: nl-be
    weight: 1
  fr:
    contentDir: content/fr
    languageName: Français
    languageCode: fr-be
    weight: 2
  en:
    contentDir: content/en
    languageName: English
    languageCode: en-us
    weight: 3
