baseURL: ""
languageCode: "en-us"
title: "DAP Rosdamhoeve"

defaultContentLang: nl
defaultContentLanguageInSubdir: true

languages:
  nl:
    contentDir: content/nl
    languageName: Nederlands
    weight: 1
  fr:
    contentDir: content/fr
    languageName: Français
    weight: 2
  en:
    contentDir: content/en
    languageName: English
    weight: 3
